### GET request with a header
GET http://localhost:8083/notices
Accept: application/json


### Send POST request with json body
POST http://localhost:8083/register
Content-Type: application/json

{
  "name": "Eazy Bytes 2",
  "email": "tutor@eazybytes.com",
  "mobileNumber": "1236546278",
  "pwd": "12345",
  "role": "user"
}

### GET Keycloak configuration
GET http://fedora:8180/realms/eazybankdev/.well-known/openid-configuration
Accept: application/json

### Send POST request to token endpoint
POST http://fedora:8180/realms/eazybankdev/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = eazybankapi &
client_secret = Q1LRmDcfOemeT5QikaHTymC8N4S9Zy3H &
scope = openid email profile address &
grant_type = client_credentials




