server:
  port: 8083
spring:
  application:
    name: SpringSecOauth2GitHubApplication
#oauth2:
#  client-id: ${OAUTH2_GITHUB_CLIENT_ID:clientId}
#  client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET:clientSecret}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID:clientId}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET:clientSecret}