server:
  port: 8083
spring:
  application:
    name: springsecuritysection8
  security:
    user:
      password: udemy
  datasource:
    url: jdbc:mysql://fedora/eazybank
    username: root
    password: admin01
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG